### model
model_name_or_path: Qwen/Qwen3-VL-4B-Instruct
custom_model_architecture: Qwen3VLForConditionalGenerationSlotQuery #Qwen3VLForConditionalGenerationTimechat Qwen3VLForConditionalGenerationSlotQuery 
image_max_pixels: 65536 #262144
video_max_pixels: 65536
#video_min_pixels: 65536


hybrid_slot_num_slots: 8
hybrid_n_query_groups: 4
per_frame_query: true
append_query: true
pass_individual_frames: true


#video_maxlen: 32

trust_remote_code: true


use_fast_tokenizer: true






### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
#deepspeed: examples/deepspeed/ds_z2_config.json
disable_gradient_checkpointing: false
gradient_checkpointing: true
use_unsloth_gc: true
enable_liger_kernel: true

### dataset
dataset: roboG_stagepoc_grounding_only_video_train  #,eo1m,sav,video_espresso,fsd
template: qwen3_vl_nothink_slot_query_hybrid
cutoff_len: 4096
max_samples: 32
overwrite_cache: true
preprocessing_num_workers: 1
dataloader_num_workers: 4

### output
output_dir: saves/qwen3_5vl-4b/full/sft/${dataset}
logging_steps: 10
save_strategy: epoch
#save_steps: 400
plot_loss: true
overwrite_output_dir: true
save_only_model: false
#report_to: wandb
run_name: ${model_name_or_path}_${dataset}_${stage}

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.04
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

##optimizationspip
flash_attn: fa2
#use_unsloth: trues
#optim: adamw_bnb_8bit
#pure_bf16: true


evaluators:
  - bbox_evaluator
  - label_evaluator

#tokenized_path: /data/roboG_debug/${dataset}/



### eval
#val_size: 0.1
do_eval: true
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 100
eval_dataset: roboG_stagepoc_grounding_only_video_train
#predict_with_generate: true
#do_predict: true